In [137]:
import numpy as np
import pandas as pd

### 1:Loading the dataset



Load the dataset (replace 'dataset.csv' with the actual path to your file) 
Assuming the data columns are in the order: CustomerID, Gender, Age, Annual Income, Spending Score 

data = np.genfromtxt('dataset.csv', delimiter=',', skip_header=1)

You will notice the gender column is all NaNs. Why is that ? How can you solve for it ?


### Import the data from MallCus.csv using the Numpy genformtxt function

In [138]:
data = np.genfromtxt('/Users/mathavana/Projects/NTU_DS_AI/kaggle_data/MallCus.csv', delimiter=',', skip_header=1, dtype=['int', 'S10', 'int','int', 'int'])

In [139]:
dat = pd.read_csv('/Users/mathavana/Projects/NTU_DS_AI/kaggle_data/MallCus.csv')

In [140]:
dat = pd.DataFrame(dat)

In [141]:
Cust_data = np.array(dat)

In [142]:
Cust_data

array([[1, 'Male', 19, 15, 39],
       [2, 'Male', 21, 15, 81],
       [3, 'Female', 20, 16, 6],
       [4, 'Female', 23, 16, 77],
       [5, 'Female', 31, 17, 40],
       [6, 'Female', 22, 17, 76],
       [7, 'Female', 35, 18, 6],
       [8, 'Female', 23, 18, 94],
       [9, 'Male', 64, 19, 3],
       [10, 'Female', 30, 19, 72],
       [11, 'Male', 67, 19, 14],
       [12, 'Female', 35, 19, 99],
       [13, 'Female', 58, 20, 15],
       [14, 'Female', 24, 20, 77],
       [15, 'Male', 37, 20, 13],
       [16, 'Male', 22, 20, 79],
       [17, 'Female', 35, 21, 35],
       [18, 'Male', 20, 21, 66],
       [19, 'Male', 52, 23, 29],
       [20, 'Female', 35, 23, 98],
       [21, 'Male', 35, 24, 35],
       [22, 'Male', 25, 24, 73],
       [23, 'Female', 46, 25, 5],
       [24, 'Male', 31, 25, 73],
       [25, 'Female', 54, 28, 14],
       [26, 'Male', 29, 28, 82],
       [27, 'Female', 45, 28, 32],
       [28, 'Male', 35, 28, 61],
       [29, 'Female', 40, 29, 31],
       [30, 'Female', 23

### 2.  Understand Customer Demographics
Calculate the average Age, Annual Income, and Spending Score to understand the typical customer profile.
Analyze customer distribution by gender. Does one gender tend to spend more or earn more on average?
Hint: Use NumPy operations like mean(), min(), and max() for this analysis.

In [143]:
avg_income = np.mean(Cust_data[:, 3])
avg_spend =np.mean(Cust_data[:, 4])
avg_age = np.mean(Cust_data[:, 2])
No_male = np.sum(Cust_data[:, 1] == 'Male')
No_female=np.sum(Cust_data[:, 1]== 'Female')
print(No_male,No_female,avg_age,avg_income, avg_spend)

88 112 38.85 60.56 50.2


### 3: Identify High-Value Customers
Filter customers with a Spending Score > 80 and calculate their average Annual Income.
Identify the top 10 customers by Spending Score. What do they have in common (e.g., age group, gender)?
Hint: Use boolean indexing and NumPy’s argsort() for ranking.

In [144]:
cust_spendscore_80 = Cust_data[Cust_data[:,4] >80]
avg_income_spendscore_80 = np.mean (cust_spendscore_80[:,3])

In [145]:
avg_income_spendscore_80

69.06666666666666

In [146]:
sorted_data = Cust_data[np.argsort(-Cust_data[:, 4])]

In [147]:
top_10_spend_customers = sorted_data[:10]

In [148]:
age_group = top_10_spend_customers[:, 2]
gender = top_10_spend_customers[:, 1]


avg_age = np.mean(age_group)


male_count = np.sum(gender == 'Male')
female_count = np.sum(gender == 'Female')

In [149]:
print (avg_age,
male_count,
female_count)

30.5 5 5


### 4: Explore Relationships Between Features
Compute the pairwise correlations between Age, Annual Income, and Spending Score to uncover key drivers of spending.
Filter young adults (18-25) and calculate their average Spending Score. Compare this with older age groups.
Hint: Correlation can be computed using NumPy’s corrcoef().

In [150]:
young_adults = Cust_data [np.where ((Cust_data[:,2] >=18) & (Cust_data[:,2]<=25))]
youngadults_spendscore = np.mean (young_adults[:,2])
print (youngadults_spendscore)

21.157894736842106


In [151]:
non_young_adults = Cust_data [np.where (Cust_data[:,2] >25)]
non_youngadults_spendscore = np.mean (non_young_adults[:,2])
print (non_youngadults_spendscore)

43.0


In [152]:
corr_young_adults = np.corrcoef(young_adults[:, 3].astype(int), young_adults[:, 4].astype(int))
print(corr_young_adults)

[[ 1.         -0.67579731]
 [-0.67579731  1.        ]]


In [153]:
corr_non_youngadults = np.corrcoef(non_young_adults[:, 3].astype(int), non_young_adults[:, 4].astype(int))
print(corr_non_youngadults)

[[1.         0.16393573]
 [0.16393573 1.        ]]


In [154]:
low_spending = Cust_data [np.where ((Cust_data[:,4] >=1) & (Cust_data[:,4]<=33))]
avg_age_low_spending = np.mean(low_spending[:,2])
avg_age_low_spending

42.87755102040816

### 5: Customer Segmentation
Group customers into three segments based on their Spending Score:
Low (1-33)
Medium (34-66)
High (67-100)
Compute the average Age and Annual Income for each segment. What are the characteristics of each group?
Propose marketing strategies for each segment.
Hint: Use NumPy’s slicing and aggregation techniques.

Instead of finding segment wide avg use for loop based on the segments classifications

In [155]:
# Define the segments
segments = [
    ("Low", 0, 33),
    ("Medium", 34, 66),
    ("High", 67, 100)
]

# Iterate over the segments
for name, min_score, max_score in segments:
    segment = Cust_data[(Cust_data[:, 4] >= min_score) & (Cust_data[:, 4] <= max_score)]
    avg_age = np.mean(segment[:, 2])
    avg_income = np.mean(segment[:, 3])

    print(f"{name} Spending Score Segment:")
    print(f"Average Age: {avg_age:.2f}")
    print(f"Average Annual Income: {avg_income:.2f}\n")

Low Spending Score Segment:
Average Age: 42.88
Average Annual Income: 67.00

Medium Spending Score Segment:
Average Age: 42.01
Average Annual Income: 53.86

High Spending Score Segment:
Average Age: 30.18
Average Annual Income: 66.07



### 6: Find Behavioral Similarities
Normalize the dataset (subtract the mean and divide by the standard deviation for each column).
Compute the Euclidean distance between each customer and the customer with the highest Spending Score. Identify customers who exhibit similar behavior.
Hint: Use NumPy’s vectorized operations for distance calculations.

In [156]:
norm_cust_data = Cust_data[:, 2:]
#normalize the age
mean_age = np.mean (norm_cust_data[:, 0])
std_age= np.std (norm_cust_data[:, 0])
norm_age = mean_age/std_age

#normalize the salary
mean_salary = np.mean (norm_cust_data[:, 1])
std_salary= np.std (norm_cust_data[:, 1])
norm_salary = mean_salary/std_salary

#normalise the spending score
mean_spend = np.mean (norm_cust_data[:, 2])
std_spend= np.std (norm_cust_data[:, 2])
norm_spend = mean_spend/std_spend

norm_cust_data[:,:]=[norm_age,norm_salary,norm_spend]
norm_cust_data


array([[2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.948842347718861],
       [2.7881358938803826, 2.311540630642533, 1.9488423477188

### Below Code is recommended by meta.ai

In [157]:
# Assuming norm_cust_data is a list or a DataFrame, convert it to a NumPy array
norm_cust_data = np.array(norm_cust_data, dtype=np.float64)

# Find the customer with the highest Spending Score
max_spending_idx = np.argmax(norm_cust_data[:, 2])
max_spending_customer = norm_cust_data[max_spending_idx]

# Compute the Euclidean distance between each customer and the customer with the highest Spending Score
distances = np.linalg.norm(norm_cust_data - max_spending_customer[np.newaxis, :], axis=1)

# Print the customers with the smallest distances (i.e., similar behavior)
similar_customers = Cust_data[np.argsort(distances)[:10]]  # Show the top 10 similar customers
print(similar_customers)

[[193 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [194 'Female' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [195 'Female' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [196 'Female' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [197 'Female' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [198 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [199 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [200 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [1 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]
 [2 'Male' 2.7881358938803826 2.311540630642533 1.948842347718861]]
